INSERT INTO PRENDA_TALLA
VALUES (1, 1, 10);

INSERT INTO PRENDA_TALLA
VALUES (2, 2, 20);

INSERT INTO PRENDA_TALLA
VALUES (3, 3, 15);

INSERT INTO PRENDA_TALLA
VALUES (4, 4, 8);

INSERT INTO PRENDA_TALLA
VALUES (5, 5, 5);

INSERT INTO PRENDA_TALLA
VALUES (6, 1, 12);

INSERT INTO PRENDA_TALLA
VALUES (7, 2, 14);

INSERT INTO PRENDA_TALLA
VALUES (8, 3, 9);

INSERT INTO PRENDA_TALLA
VALUES (9, 4, 6);

INSERT INTO PRENDA_TALLA
VALUES (10, 5, 4);