INSERT INTO MATERIAL
VALUES (1,'Algodón');

INSERT INTO MATERIAL
VALUES (2,'Poliéster');

INSERT INTO MATERIAL
VALUES (3,'Cuero');

INSERT INTO MATERIAL
VALUES (4,'Lana');

INSERT INTO MATERIAL
VALUES (5,'Sintético');

INSERT INTO MATERIAL
VALUES (6,'Seda');

INSERT INTO MATERIAL
VALUES (7,'Lino');

INSERT INTO MATERIAL
VALUES (8,'Spandex');

INSERT INTO MATERIAL
VALUES (9,'Gamuza');

INSERT INTO MATERIAL
VALUES (10,'Mezclilla');