INSERT INTO MARCA
VALUES (1,'Nike');

INSERT INTO MARCA
VALUES (2,'Adidas');

INSERT INTO MARCA
VALUES (3,'Zara');

INSERT INTO MARCA
VALUES (4,'Pull And Bear');

INSERT INTO MARCA
VALUES (5,'Puma');

INSERT INTO MARCA
VALUES (6,'Levis');

INSERT INTO MARCA
VALUES (7,'Under Armour');

INSERT INTO MARCA
VALUES (8,'GAP');

INSERT INTO MARCA
VALUES (9,'Converse');

INSERT INTO MARCA
VALUES (10,'Reebook');

INSERT INTO MARCA 
VALUES (11, 'Forever 21');

INSERT INTO MARCA 
VALUES (12, 'American Eagle');

INSERT INTO MARCA 
VALUES (13, 'Old Navy');

INSERT INTO MARCA 
VALUES (14, 'Aeropostale');

INSERT INTO MARCA 
VALUES (15, 'Uniqlo');

INSERT INTO MARCA 
VALUES (16, 'Hollister');

INSERT INTO MARCA 
VALUES (17, 'Abercrombie & Fitch');

INSERT INTO MARCA 
VALUES (18, 'Banana Republic');

INSERT INTO MARCA 
VALUES (19, 'Express');

INSERT INTO MARCA 
VALUES (20, 'Guess');
