INSERT INTO PRENDA_PROVEEDOR
VALUES (1,1);

INSERT INTO PRENDA_PROVEEDOR
VALUES (2,2);

INSERT INTO PRENDA_PROVEEDOR
VALUES (3,3);

INSERT INTO PRENDA_PROVEEDOR
VALUES (4,4);

INSERT INTO PRENDA_PROVEEDOR
VALUES (5,5);

INSERT INTO PRENDA_PROVEEDOR
VALUES (6,6);

INSERT INTO PRENDA_PROVEEDOR
VALUES (7,7);

INSERT INTO PRENDA_PROVEEDOR
VALUES (8,8);

INSERT INTO PRENDA_PROVEEDOR
VALUES (9,9);

INSERT INTO PRENDA_PROVEEDOR
VALUES (10,10);
