INSERT INTO PRENDA_PROVEEDOR
VALUES (1,1);

INSERT INTO PRENDA_PROVEEDOR
VALUES (2,2);

INSERT INTO PRENDA_PROVEEDOR
VALUES (3,3);

INSERT INTO PRENDA_PROVEEDOR
VALUES (4,4);

INSERT INTO PRENDA_PROVEEDOR
VALUES (5,5);

INSERT INTO PRENDA_PROVEEDOR
VALUES (6,6);

INSERT INTO PRENDA_PROVEEDOR
VALUES (7,7);

INSERT INTO PRENDA_PROVEEDOR
VALUES (8,8);

INSERT INTO PRENDA_PROVEEDOR
VALUES (9,9);

INSERT INTO PRENDA_PROVEEDOR
VALUES (10,10);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (11, 11);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (12, 12);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (13, 13);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (14, 14);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (15, 15);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (16, 16);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (17, 17);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (18, 18);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (19, 19);

INSERT INTO PRENDA_PROVEEDOR 
VALUES (20, 20);

