INSERT INTO DEPARTAMENTO
VALUES (1,'Hombre');

INSERT INTO DEPARTAMENTO
VALUES (2,'Mujer');

INSERT INTO DEPARTAMENTO
VALUES (3,'Niños');

INSERT INTO DEPARTAMENTO
VALUES (4,'Calzado');

INSERT INTO DEPARTAMENTO
VALUES (5,'Accesorios');
