INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (1,1);

INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (2,1);

INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (3,2);

INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (4,3);

INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (5,3);

INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (6,1);

INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (7,2);

INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (8,3);

INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (9,2);

INSERT INTO CATEGORIA_DEPARTAMENTO
VALUES (10,1);