INSERT INTO CATEGORIA
VALUES (1,'Camisetas');

INSERT INTO CATEGORIA
VALUES (2,'Pantalones');

INSERT INTO CATEGORIA
VALUES (3,'Zapatos');

INSERT INTO CATEGORIA
VALUES (4,'Accesorios');

INSERT INTO CATEGORIA
VALUES (5,'Abrigos');

INSERT INTO CATEGORIA
VALUES (6,'Ropa Interior');

INSERT INTO CATEGORIA
VALUES (7,'Blusas');

INSERT INTO CATEGORIA
VALUES (8,'Faldas');

INSERT INTO CATEGORIA
VALUES (9,'Sueteres');

INSERT INTO CATEGORIA
VALUES (10,'Chaquetas');

INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (11, 'Ropa Casual');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (12, 'Sudaderas');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (13, 'Kimonos');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (14, 'Chalecos');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (15, 'Túnicas');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (16, 'Leotardos');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (17, 'Ropa étnica');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (18, 'Ropa de Alta Costura');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (19, 'Ropa de Yoga');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (20, 'Ropa de Danza');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (21, 'Ropa para Mascotas');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (22, 'Uniformes Escolares');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (23, 'Mallas Deportivas');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (24, 'Ropa de Carnaval');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (25, 'Monos');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (26, 'Ropa de Gala');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (27, 'Ropa Vintage');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (28, 'Trajes Tradicionales');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (29, 'Ropa de Lactancia');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (30, 'Ropa de Maternidad');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (31, 'Ropa de Chef');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (32, 'Ropa de Laboratorio');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (33, 'Ropa para Ciclismo');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (34, 'Ropa de Montaña');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (35, 'Ropa de Piel');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (36, 'Ropa de Invierno');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (37, 'Ropa de Pesca');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (38, 'Ropa de Golf');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (39, 'Ropa de Camuflaje');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (40, 'Ropa de Camping');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (41, 'Ropa de Escalada');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (42, 'Ropa Bohemia');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (43, 'Ropa de Playa');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (44, 'Ropa Retro');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (45, 'Ropa Deportiva Técnica');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (46, 'Ropa de Patinaje');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (47, 'Ropa de Tiro');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (48, 'Ropa de Esquí');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (49, 'Ropa de Piloto');
INSERT INTO CATEGORIA (CATEGORIA_ID, NOMBRE_CATEGORIA) VALUES (50, 'Ropa Militar');
