INSERT INTO CATEGORIA
VALUES (1,'Camisetas');

INSERT INTO CATEGORIA
VALUES (2,'Pantalones');

INSERT INTO CATEGORIA
VALUES (3,'Zapatos');

INSERT INTO CATEGORIA
VALUES (4,'Accesorios');

INSERT INTO CATEGORIA
VALUES (5,'Abrigos');

INSERT INTO CATEGORIA
VALUES (6,'Ropa Interior');

INSERT INTO CATEGORIA
VALUES (7,'Blusas');

INSERT INTO CATEGORIA
VALUES (8,'Faldas');

INSERT INTO CATEGORIA
VALUES (9,'Sueteres');

INSERT INTO CATEGORIA
VALUES (10,'Chaquetas');