INSERT INTO MARCA
VALUES (1,'Nike');

INSERT INTO MARCA
VALUES (2,'Adidas');

INSERT INTO MARCA
VALUES (3,'Zara');

INSERT INTO MARCA
VALUES (4,'Pull And Bear');

INSERT INTO MARCA
VALUES (5,'Puma');

INSERT INTO MARCA
VALUES (6,'Levis');

INSERT INTO MARCA
VALUES (7,'Under Armour');

INSERT INTO MARCA
VALUES (8,'GAP');

INSERT INTO MARCA
VALUES (9,'Converse');

INSERT INTO MARCA
VALUES (10,'Reebook');