-- Tablas de entidades base sin dependencias
CREATE TABLE CATEGORIA (
    CATEGORIA_ID NUMBER(2) NOT NULL,
    NOMBRE_CATEGORIA VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY(CATEGORIA_ID)
);

CREATE TABLE DEPARTAMENTO (
    DEPARTAMENTO_ID NUMBER(2) NOT NULL,
    NOMBRE_DEPARTAMENTO VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(DEPARTAMENTO_ID)
);

CREATE TABLE PROVEEDOR (
    PROVEEDOR_ID INTEGER NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR2(30) NOT NULL,
    TELEFONO NUMBER(10) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    DIRECCION VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PROVEEDOR PRIMARY KEY(PROVEEDOR_ID)
);

CREATE TABLE MATERIAL (
    MATERIAL_ID NUMBER(2) NOT NULL,
    NOMBRE_MATERIAL VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_MATERIAL PRIMARY KEY(MATERIAL_ID)
);

CREATE TABLE MARCA (
    MARCA_ID NUMBER(2) NOT NULL,
    NOMBRE_MARCA VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_MARCA PRIMARY KEY(MARCA_ID)
);

CREATE TABLE EMPLEADO (
    EMPLEADO_ID NUMBER(5) NOT NULL,
    NOMBRE VARCHAR2(15) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(15) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(15) NOT NULL,
    TELEFONO NUMBER(10) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    DIRECCION VARCHAR2(40) NOT NULL,
    FECHA_CONTRATACION DATE NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY(EMPLEADO_ID)
);

CREATE TABLE TALLA (
    TALLA_ID NUMBER(2) NOT NULL,
    NOMBRE_TALLA VARCHAR2(5) NOT NULL,
    CONSTRAINT PK_TALLA PRIMARY KEY(TALLA_ID)
);

-- Tablas con claves foráneas que dependen de las tablas anteriores
CREATE TABLE PRENDA (
    PRENDA_ID NUMBER(5) NOT NULL,
    NOMBRE_PRENDA VARCHAR2(30) NOT NULL,
    PRECIO NUMBER(6,2) NOT NULL, -- Modificado para permitir precios como 150.00
    CATEGORIA_ID NUMBER(2) NOT NULL,
    MATERIAL_ID NUMBER(2) NOT NULL,
    MARCA_ID NUMBER(2) NOT NULL,
    CONSTRAINT PK_PRENDA PRIMARY KEY(PRENDA_ID),
    CONSTRAINT FK_CATEGORIA FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIA(CATEGORIA_ID),
    CONSTRAINT FK_MATERIAL FOREIGN KEY(MATERIAL_ID) REFERENCES MATERIAL(MATERIAL_ID),
    CONSTRAINT FK_MARCA FOREIGN KEY(MARCA_ID) REFERENCES MARCA(MARCA_ID)
);

CREATE TABLE DETALLE_VENTA (
    DETALLE_VENTA_ID NUMBER(5) NOT NULL,
    TOTAL NUMBER(6,2) NOT NULL,
    FECHA DATE NOT NULL,
    EMPLEADO_ID NUMBER(5) NOT NULL,
    CONSTRAINT PK_DETALLE_VENTA PRIMARY KEY(DETALLE_VENTA_ID),
    CONSTRAINT FK_EMPLEADO FOREIGN KEY(EMPLEADO_ID) REFERENCES EMPLEADO(EMPLEADO_ID)
);

-- Tablas de relaciones muchos a muchos
CREATE TABLE CATEGORIA_DEPARTAMENTO (
    ID_CATEGORIA NUMBER(2) NOT NULL,
    ID_DEPARTAMENTO NUMBER(2) NOT NULL,
    CONSTRAINT PK_CATEGORIA_DEPARTAMENTO PRIMARY KEY(ID_CATEGORIA, ID_DEPARTAMENTO),
    CONSTRAINT FK_CAT_DEP_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(CATEGORIA_ID),
    CONSTRAINT FK_CAT_DEP_DEPARTAMENTO FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(DEPARTAMENTO_ID)
);

CREATE TABLE PRENDA_PROVEEDOR (
    ID_PRENDA NUMBER(5) NOT NULL,
    ID_PROVEEDOR INTEGER NOT NULL,
    CONSTRAINT PK_PRENDA_PROVEEDOR PRIMARY KEY(ID_PRENDA, ID_PROVEEDOR),
    CONSTRAINT FK_PRENDA FOREIGN KEY(ID_PRENDA) REFERENCES PRENDA(PRENDA_ID),
    CONSTRAINT FK_PROVEEDOR FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(PROVEEDOR_ID)
);

CREATE TABLE PRENDA_TALLA (
    ID_PRENDA NUMBER(5) NOT NULL,
    ID_TALLA NUMBER(2) NOT NULL,
    STOCK INTEGER NOT NULL,
    CONSTRAINT PK_PRENDA_TALLA PRIMARY KEY(ID_PRENDA, ID_TALLA),
    CONSTRAINT FK_PT_PRENDA FOREIGN KEY(ID_PRENDA) REFERENCES PRENDA(PRENDA_ID),
    CONSTRAINT FK_PT_TALLA FOREIGN KEY(ID_TALLA) REFERENCES TALLA(TALLA_ID)
);

CREATE TABLE VENTA_PRENDA (
    ID_PRENDA NUMBER(5) NOT NULL,
    ID_DETALLE_VENTA NUMBER(5) NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    PRECIO_UNITARIO NUMBER(6,2) NOT NULL, 
    SUBTOTAL NUMBER(8,2) NOT NULL, 
    CONSTRAINT PK_VENTA_PRENDA PRIMARY KEY(ID_PRENDA, ID_DETALLE_VENTA),
    CONSTRAINT FK_VP_PRENDA FOREIGN KEY(ID_PRENDA) REFERENCES PRENDA(PRENDA_ID),
    CONSTRAINT FK_VP_DETALLE_VENTA FOREIGN KEY(ID_DETALLE_VENTA) REFERENCES DETALLE_VENTA(DETALLE_VENTA_ID)
);

CREATE TABLE DETALLE_DEVOLUCION (
    DETALLE_DEVOLUCION_ID NUMBER(5) NOT NULL,
    FECHA_DEVOLUCION DATE NOT NULL,
    MOTIVO VARCHAR2(50) NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    ID_PRENDA NUMBER(5) NOT NULL,
    ID_DETALLE_VENTA NUMBER(5) NOT NULL,
    CONSTRAINT PK_DEVOLUCION PRIMARY KEY(DETALLE_DEVOLUCION_ID),
    CONSTRAINT FK_DEVOLUCION_VENTA_PRENDA FOREIGN KEY(ID_PRENDA, ID_DETALLE_VENTA) REFERENCES VENTA_PRENDA(ID_PRENDA, ID_DETALLE_VENTA)
);
